### PR TITLE
codeclimate config

### PR DESCRIPTION
**Pull request by mixman**

### CODE REVIEW

**Comment by staltz** [comment]
Looks good to me. @petuomin can you merge?

**Comment by petuomin** [comment]
The codeclimate runner now reports, that coverage info is sent to codeclimate servers succesfully, so I'll merge this branch. Codeclimate only cares about reports sent from default branch (which is master).

**Comment by staltz** [comment]
How about adding the badge to README.md too?

**Comment by petuomin** [comment]
I'll check that the coverage will actually be reported correctly before adding the badge. There is a slight delay on the update, so i'm not sure if it works yet.

**Pull request merged**
